export const colors = {
  foreground: "#333333",
  background: "#ffffff",
  primary: "#3b82f6",
  primaryForeground: "#ffffff",
  secondary: "#e3e4e6",
  secondaryForeground: "#4b5563",
  accent: "#e0f2fe",
  accentForeground: "#1e3a8a",
  muted: "#f9fafb",
  mutedForeground: "#6b7280",
  border: "#e5e7eb",
  input: "#e5e7eb",
  destructive: "#ef4444",
  destructiveForeground: "#ffffff",
  tabInactive: "#a0a0a0",
};
